    # Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_cpp_dense <- function(X) {
    .Call(`_gammaPartition_gamma_cpp_dense`, X)
}

gamma_cpp_sparse <- function(X) {
    .Call(`_gammaPartition_gamma_cpp_sparse`, X)
}

gamma_cpp_diagonal <- function(X) {
    .Call(`_gammaPartition_gamma_cpp_diagonal`, X)
}

k_gamma_cpp <- function(X, k, class_col) {
    .Call(`_gammaPartition_k_gamma_cpp`, X, k, class_col)
}

k_gamma_diagonal <- function(X, k, class_col) {
    .Call(`_gammaPartition_k_gamma_diagonal`, X, k, class_col)
}

naiveBayesPrediction <- function(X_Test, mu, sigma, prior, class_labels) {
    .Call(`_gammaPartition_naiveBayesPrediction`, X_Test, mu, sigma, prior, class_labels)
}

assignCluster <- function(X, cluster_centroids, k) {
    .Call(`_gammaPartition_assignCluster`, X, cluster_centroids, k)
}

gamma_cpp <- function(X, Flag1) {
    .Call(`_gammaPartition_gamma_cpp`, X, Flag1)
}

